# Generated by Django 4.2.7 on 2023-11-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(null=True, verbose_name="Last activity"),
        ),
    ]
