# Generated by Django 5.0 on 2024-11-02 07:41

import gabgabgurus.apps.users.models
import gabgabgurus.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to=gabgabgurus.apps.users.models.avatar_upload_to,
                validators=[
                    gabgabgurus.common.validators.MaxFileWeightValidator(307200),
                    gabgabgurus.common.validators.MaxImageSizeValidator(limit_height=2600, limit_width=2600),
                ],
                verbose_name="avatar",
            ),
        ),
    ]
