# Generated by Django 4.2.6 on 2023-11-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "Hobby",
                "verbose_name_plural": "Hobbies",
                "ordering": ("-name",),
            },
        ),
    ]
