x-base-service: &base-service
    platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
    restart: on-failure
    profiles:
        - default
    networks:
        - default

x-web-and-back-shared-network: &web-and-back-shared-network
    networks:
        - default
        - ggg_external

x-common-healthcheck: &common-healthcheck
    interval: 3s
    timeout: 2s
    retries: 20

services:
    app:
        <<: [ *web-and-back-shared-network, *base-service ]
        environment:
            APP_HOST: 0.0.0.0
            APP_PORT: 8000
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_HOST: redis
            REDIS_PORT: 6379
        env_file: .env
        volumes:
            - ggg_backend_static:/app/src/gabgabgurus/staticfiles
            - ggg_backend_media:/app/src/gabgabgurus/media
        healthcheck:
            test: [ "CMD", "./scripts/wait-for-it.sh", "app:8000" ]
            <<: *common-healthcheck
        depends_on:
            - postgres
            - redis

    postgres:
        <<: *base-service
        image: ${POSTGRES_IMG}
        env_file: .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        profiles:
            - default
            - db

    redis:
        <<: *base-service
        image: ${REDIS_IMG}
        env_file: .env
        volumes:
            - redis_data:/data
        profiles:
            - default
            - db

volumes:
    redis_data:
    postgres_data:
    ggg_backend_static:
        external: true
        name: ggg_backend_static
    ggg_backend_media:
        external: true
        name: ggg_backend_media

networks:
    ggg_external:
        external: true
        name: ggg_external
