x-base-dev-service: &base-dev-service
    restart: "no"
    networks:
        - default

services:
    app:
        <<: *base-dev-service
        build:
            context: .
            dockerfile: deploy/app/Dockerfile
            args:
                env: ${ENVIRONMENT}
                img: ${PYTHON_IMG}
        volumes:
            - ./src/gabgabgurus:/app/src/gabgabgurus
        networks:
            - default
            - gabgabgurus_external

    postgres:
        <<: *base-dev-service
        ports:
            - ${POSTGRES_PORT}:5432

    redis:
        <<: *base-dev-service
        ports:
            - ${REDIS_PORT}:6379

networks:
    gabgabgurus_external:
        external: true
        name: gabgabgurus_external
