# Generated by Django 4.2.6 on 2023-11-09 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userchannel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagestatus",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_statuses",
                to="chats.message",
            ),
        ),
        migrations.AddField(
            model_name="messagestatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chats.channel"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="participants",
            field=models.ManyToManyField(through="chats.UserChannel", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="userchannel",
            constraint=models.UniqueConstraint(
                fields=("user", "channel"),
                name="unique_user_channel",
                violation_error_message="A user_channel record with such fields values already exists",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagestatus",
            constraint=models.UniqueConstraint(
                fields=("user", "message"),
                name="unique_user_message",
                violation_error_message="A user_message record with such fields values already exists",
            ),
        ),
    ]
