# Generated by Django 4.2.6 on 2023-11-09 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ("-name",),
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CountryLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_official", models.BooleanField(default=False, verbose_name="is_official")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_languages",
                        to="languages.country",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="country_languages",
                        to="languages.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country language",
                "verbose_name_plural": "Country languages",
            },
        ),
        migrations.AddField(
            model_name="country",
            name="languages",
            field=models.ManyToManyField(
                related_name="countries", through="languages.CountryLanguage", to="languages.language"
            ),
        ),
        migrations.AddConstraint(
            model_name="countrylanguage",
            constraint=models.UniqueConstraint(
                fields=("country", "language"), name="unique_country_language"
            ),
        ),
    ]
