# Generated by Django 4.2.7 on 2023-12-02 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("name",), "verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
    ]
