# Generated by Django 4.2.6 on 2023-11-09 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlanguage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_languages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userlanguage",
            index=models.Index(fields=["language", "is_speaking"], name="language_speaking_idx"),
        ),
        migrations.AddIndex(
            model_name="userlanguage",
            index=models.Index(fields=["language", "is_learning"], name="language_learning_idx"),
        ),
        migrations.AddConstraint(
            model_name="userlanguage",
            constraint=models.UniqueConstraint(
                fields=("user", "language"),
                name="unique_user_language",
                violation_error_message="A user_language record with such fields values already exists",
            ),
        ),
    ]
