# Generated by Django 5.0 on 2024-11-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_details", "0003_feedbackmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackmessage",
            options={
                "ordering": ("first_name",),
                "verbose_name": "FeedbackMessage",
                "verbose_name_plural": "FeedbackMessages",
            },
        ),
        migrations.RemoveField(
            model_name="feedbackmessage",
            name="name",
        ),
        migrations.AddField(
            model_name="feedbackmessage",
            name="first_name",
            field=models.CharField(max_length=250, null=True, verbose_name="first_name"),
        ),
    ]
